### ISSUE TITLE
Fast user switching

### ISSUE THREAD

**Issue by Maigre** [DeedleFake/trayscale#109] opened 2024-04-29 19:26 UTC
Hi, thanks for the app 
I'd suggest adding "Fast user switching" directly from the tray icon,
that would be awesome !

CLI reference: 
```tailscale switch --list```
```tailscale switch <Account>```

official doc here: https://tailscale.com/kb/1225/fast-user-switching

Thank you for considering :)

**Comment by Pastitas** [comment] 2024-05-15 17:39
this is a duplicate of #61

**Comment by DeedleFake** [comment] 2024-05-21 14:59
Closing as a duplicate.

This is a planned feature, but my time is fairly limited and there are a few UI issues that have delayed this. I'll get back to it when I can.

**Closed by DeedleFake** 2024-05-21 14:59 UTC
