### ISSUE TITLE
Add ability to share files

### ISSUE THREAD

**Issue by aaron1857** [DeedleFake/trayscale#57] opened 2023-04-08 19:19 UTC
Would it be possible to add the ability to share files within this app? It's possible to do this with the official tailscale command line, but it'd be nice it could be done graphically.

**Comment by DeedleFake** [comment] 2023-04-09 04:36
This is a duplicate of a bullet point on #5, but I'll leave it open since it makes sense for it to be its own issue. I've been planning on hopefully getting to this one relatively soon, but no promises.

**Closed** 2023-08-16 19:53 UTC
Labels: enhancement
